locale = "fr"
label = "Français"
weight = 1
title = "Le Site de François"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 janvier 2006"
  description = "Le site des sorties en famille"

[params.author]
  name = "François"
  image = "images/author.jpeg"
  headline = "Le site des sorties en famille"
  bio = "Le site des sorties en famille"
