[[main]]
  name = "Home"
  pageRef = "accueil"
  weight = 5

[[main]]
  name = "Travels"
  pageRef = "voyages"
  weight = 10

[[main]]
  name = "Europe"
  parent = "Travels"
  pageRef = "voyages/europe"
  weight = 1

[[main]]
  name = "Asia"
  parent = "Travels"
  pageRef = "voyages/asie"
  weight = 2

[[main]]
  name = "America"
  parent = "Travels"
  pageRef = "voyages/amerique"
  weight = 3

[[main]]
  name = "Outings"
  pageRef = "sorties"
  weight = 20

[[main]]
  name = "Music"
  parent = "Outings"
  pageRef = "sorties/musique"
  weight = 1

[[main]]
  name = "Restaurants"
  parent = "Outings"
  pageRef = "sorties/resto"
  weight = 2

[[main]]
  name = "Theatre"
  parent = "Outings"
  pageRef = "sorties/theatre"
  weight = 3

[[main]]
  name = "Events"
  parent = "Outings"
  pageRef = "sorties/evenements"
  weight = 4

[[main]]
  name = "Parks"
  parent = "Outings"
  pageRef = "sorties/parcs"
  weight = 5

[[main]]
  name = "Craft Beer"
  parent = "Outings"
  pageRef = "sorties/craft-beer"
  weight = 6

[[main]]
  name = "Speciality Coffee"
  parent = "Outings"
  pageRef = "sorties/cafe-de-specialite"
  weight = 6

[[main]]
  name = "Tech"
  pageRef = "security"
  weight = 30

[[main]]
  name = "AI"
  parent = "Tech"
  pageRef = "ai/index"
  weight = 1

[[main]]
  name = "Telco"
  parent = "Tech"
  pageRef = "telco/index"
  weight = 2

[[main]]
  name = "Security"
  parent = "Tech"
  pageRef = "security/index"
  weight = 3

[[main]]
  name = "Compliance"
  parent = "Tech"
  pageRef = "compliance/index"
  weight = 4