[[main]]
  name = "Home"
  pageRef = "accueil"
  weight = 5

[[main]]
  name = "Travels"
  pageRef = "voyages"
  weight = 10

[[main]]
  name = "Europe"
  parent = "Travels"
  url = "/en/categories/europe/"
  weight = 1

[[main]]
  name = "Asia"
  parent = "Travels"
  url = "/en/categories/asia/"
  weight = 2

[[main]]
  name = "America"
  parent = "Travels"
  url = "/en/categories/america/"
  weight = 3

[[main]]
  name = "Outings"
  pageRef = "sorties"
  weight = 20

[[main]]
  name = "Music"
  parent = "Outings"
  url = "/en/categories/music/"
  weight = 1

[[main]]
  name = "Restaurants"
  parent = "Outings"
  url = "/en/categories/restaurants/"
  weight = 2

[[main]]
  name = "Parks"
  parent = "Outings"
  url = "/en/categories/parks/"
  weight = 3

[[main]]
  name = "Must-Sees"
  pageRef = "les-incontournables"
  weight = 30

[[main]]
  name = "Miscellaneous"
  pageRef = "divers"
  weight = 40
