[[main]]
  name = "Home"
  pageRef = "accueil"
  weight = 5

[[main]]
  name = "Travels"
  pageRef = "voyages"
  weight = 10

[[main]]
  name = "Europe"
  parent = "Travels"
  url = "/en/categories/europe/"
  weight = 1

[[main]]
  name = "Asia"
  parent = "Travels"
  url = "/en/categories/asia/"
  weight = 2

[[main]]
  name = "America"
  parent = "Travels"
  url = "/en/categories/america/"
  weight = 3

[[main]]
  name = "Outings"
  pageRef = "sorties"
  weight = 20

[[main]]
  name = "Music"
  parent = "Outings"
  url = "/en/categories/music/"
  weight = 1

[[main]]
  name = "Restaurants"
  parent = "Outings"
  url = "/en/categories/restaurants/"
  weight = 2

[[main]]
  name = "Theatre"
  parent = "Outings"
  pageRef = "sorties/theatres-de-paris"
  weight = 3

[[main]]
  name = "Craft Beer"
  parent = "Outings"
  pageRef = "sorties/craft-beer"
  weight = 4

[[main]]
  name = "Speciality Coffee"
  parent = "Outings"
  pageRef = "sorties/cafe-de-specialite"
  weight = 5

[[main]]
  name = "Tech"
  pageRef = "security"
  weight = 30

[[main]]
  name = "Security"
  parent = "Tech"
  pageRef = "security/index"
  weight = 1

[[main]]
  name = "Telco"
  parent = "Tech"
  pageRef = "telco/index"
  weight = 2
