[[main]]
  name = "Accueil"
  pageRef = "accueil"
  weight = 5

[[main]]
  name = "Voyages"
  pageRef = "voyages"
  weight = 10

[[main]]
  name = "Europe"
  parent = "Voyages"
  pageRef = "voyages/europe"
  weight = 1

[[main]]
  name = "Asie"
  parent = "Voyages"
  pageRef = "voyages/asie"
  weight = 2

[[main]]
  name = "Amerique"
  parent = "Voyages"
  pageRef = "voyages/amerique"
  weight = 3

[[main]]
  name = "Sorties"
  pageRef = "sorties"
  weight = 20

[[main]]
  name = "Musique"
  parent = "Sorties"
  pageRef = "sorties/musique"
  weight = 1

[[main]]
  name = "Resto"
  parent = "Sorties"
  pageRef = "sorties/resto"
  weight = 2

[[main]]
  name = "Théâtre"
  parent = "Sorties"
  pageRef = "sorties/theatres-de-paris"
  weight = 3

[[main]]
  name = "Événements"
  parent = "Sorties"
  pageRef = "sorties/evenements"
  weight = 4

[[main]]
  name = "Bières Artisanales"
  parent = "Sorties"
  pageRef = "sorties/craft-beer"
  weight = 5

[[main]]
  name = "Café de spécialité"
  parent = "Sorties"
  pageRef = "sorties/cafe-de-specialite"
  weight = 6

[[main]]
  name = "Tech"
  url = "/en/security/"
  weight = 30

[[main]]
  name = "AI"
  parent = "Tech"
  url = "/en/ai/"
  weight = 1

[[main]]
  name = "Telco"
  parent = "Tech"
  url = "/en/telco/"
  weight = 2

[[main]]
  name = "Security"
  parent = "Tech"
  url = "/en/security/"
  weight = 3

[[main]]
  name = "Compliance"
  parent = "Tech"
  url = "/en/compliance/"
  weight = 4
